# Generated by Django 4.0.6 on 2022-08-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=100)),
                ('contacto', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('morada', models.CharField(blank=True, max_length=400, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grupo', models.CharField(choices=[('Fam', 'Família'), ('A', 'Amigos'), ('C', 'Clientes'), ('F', 'Fornecedores'), ('G', 'Ginásio'), ('O', 'Outros')], default='O', max_length=3)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
