# Generated by Django 4.0.6 on 2022-08-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactos',
            name='grupo',
            field=models.CharField(choices=[('Família', 'Família'), ('Amigos', 'Amigos'), ('Clientes', 'Clientes'), ('Fornecedores', 'Fornecedores'), ('Ginásio', 'Ginásio'), ('Outros', 'Outros')], default='O', max_length=15),
        ),
    ]
