# Generated by Django 4.0.6 on 2022-08-08 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_alter_contactos_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['grupo'],
            },
        ),
        migrations.AlterField(
            model_name='contactos',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contactos.grupo'),
        ),
    ]
